# syntax=docker/dockerfile:1
# Stage 1: Build with Bun (Bun does not ship in node:20-alpine, so we need a Bun image).
FROM oven/bun:1-alpine AS builder
WORKDIR /app

# libc6-compat is required for certain native node modules under Alpine.
RUN apk add --no-cache libc6-compat

# Install dependencies with a frozen lockfile (reproducible builds).
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# Copy source and build.
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN bun run build

# Stage 2: Runtime on Node.js 20 Alpine.
FROM node:20-alpine AS runner
WORKDIR /app

RUN apk add --no-cache libc6-compat

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# HOSTNAME=0.0.0.0 is required for Next.js standalone to be reachable from outside the container.
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

# Non-root user for runtime safety.
RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

# Copy only the standalone output + static assets + public dir.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs
EXPOSE 3000

# server.js is generated by the standalone build.
CMD ["node", "server.js"]
